name: json_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

  
  uses-material-design: true

  
  assets:
    - images/

  
  
  fonts:
    - family: SSSP
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
